# Multilingual Topic Generation for Nigerian Languages: one mT5-base model, both tasks

In [1]:
# 1. Setup + data  (Internet ON, GPU = T4)
!pip -q install bert-score sentencepiece
import os, glob, time, re, random, numpy as np, pandas as pd, torch
from transformers import AutoTokenizer, MT5ForConditionalGeneration
from transformers.optimization import Adafactor
from sklearn.metrics import f1_score
from bert_score import BERTScorer

T0 = time.time(); torch.manual_seed(0); random.seed(0); np.random.seed(0)
hits = glob.glob('/kaggle/input/**/train.csv', recursive=True)
D = os.path.dirname(hits[0]) if hits else '.'
files = [f for f in os.listdir(D) if f.endswith('.csv')]
pick = lambda *k: next((f'{D}/{f}' for f in files if any(s in f.lower() for s in k)), None)
tr, te, ss = pd.read_csv(pick('train')), pd.read_csv(pick('test')), pd.read_csv(pick('sample_sub'))
print('train cols:', tr.columns.tolist(), '| test cols:', te.columns.tolist())

ren = {'lang': 'language', 'category': 'label', 'topic': 'label', 'title': 'headline', 'content': 'text', 'article': 'text'}
for d in (tr, te):
    d.rename(columns={k: v for k, v in ren.items() if k in d.columns and v not in d.columns}, inplace=True)
    if 'language' not in d.columns: d['language'] = d.id.astype(str).str.split('_').str[0]
missing = [c for c in ['id', 'language', 'text', 'headline', 'label'] if c not in tr.columns]
assert not missing, f'train.csv is missing {missing}'

if pick('dev', 'val'):
    dv = pd.read_csv(pick('dev', 'val'))
else:  # no dev file: hold out 12% of train, stratified by language
    dv = tr.groupby('language', group_keys=False).sample(frac=.12, random_state=0)
    tr = tr.drop(dv.index)
    dv, tr = dv.reset_index(drop=True), tr.reset_index(drop=True)
for d in (tr, dv): d['label'] = d.label.astype(str).str.strip().str.lower()
LABELS = ['business','health','politics','religion','sports','entertainment','technology']
print(tr.language.value_counts().to_dict(), len(dv), len(te))

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 1.8 MB/s eta 0:00:00
train cols: ['category', 'headline', 'text', 'url', 'id', 'split', 'lang'] | test cols: ['id', 'lang', 'text']
{'hau': 1953, 'yor': 1261, 'ibo': 1193, 'pcm': 933} 728 1743

In [2]:
# 2. Metrics (pooled Macro-F1, GenScore = .5*ROUGE-L + .5*BERTScore(mBERT)) + no-training baseline
scorer = BERTScorer(model_type='bert-base-multilingual-cased', num_layers=9, device='cuda')

def toks(s): return re.sub(r'[^\w\s\u0300-\u036f]', ' ', str(s).lower()).split()
def rouge_l(c, r):
    a, b = toks(c), toks(r)
    if not a or not b: return 0.0
    prev = [0]*(len(b)+1)
    for x in a:
        cur = [0]
        for j, y in enumerate(b): cur.append(prev[j]+1 if x == y else max(prev[j+1], cur[j]))
        prev = cur
    l = prev[-1]
    return 0.0 if l == 0 else 2*(l/len(a))*(l/len(b))/(l/len(a)+l/len(b))

def evaluate(df, pt, ph):
    pt = np.array(pt)
    r = np.array([rouge_l(c, t) for c, t in zip(ph, df.headline)])
    b = scorer.score(list(ph), list(df.headline), batch_size=64)[2].numpy()
    rows = {}
    for name, m in [('ALL', np.ones(len(df), bool))] + [(l, (df.language == l).values) for l in sorted(df.language.unique())]:
        y, p = df.label.values[m], pt[m]
        f1 = f1_score(y, p, labels=sorted(set(y)|set(p)), average='macro', zero_division=0)
        g = .5*r[m].mean() + .5*b[m].mean()
        rows[name] = dict(MacroF1=f1, GenScore=g, Final=.5*f1 + .5*g)
    return pd.DataFrame(rows).T.round(4)

maj = tr.label.mode()[0]
lead = lambda t: ' '.join(str(t).split()[:12])
base = evaluate(dv, [maj]*len(dv), [lead(t) for t in dv.text])   # majority label + first 12 words as headline
base

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

     MacroF1  GenScore   Final
ALL   0.0485    0.4555  0.2520
hau   0.0332    0.4810  0.2571
ibo   0.0561    0.4507  0.2534
pcm   0.0902    0.4912  0.2907
yor   0.0815    0.3944  0.2379

In [3]:
# 3. Fine-tune ONE model on BOTH tasks (mT5-base, fp32, tied embeddings)
# v6: 8 epochs, best checkpoint also saved to /kaggle/working/mt5_best (survives interruption, reusable later)
# v5: 320-token inputs, 5 epochs w/ warmup+higher LR+grad accumulation, keeps BEST checkpoint by dev Final (not just the last epoch)
from transformers import get_linear_schedule_with_warmup

MID, MAXIN, EPOCHS, ACC_STEPS = 'google/mt5-base', 320, 8, 4
tk = AutoTokenizer.from_pretrained(MID)
model = MT5ForConditionalGeneration.from_pretrained(MID).cuda()
model.set_input_embeddings(model.shared)   # tie encoder/decoder/shared embeddings (~966M -> ~582M params)
NPARAMS = sum(p.numel() for p in model.parameters()); print(f'{NPARAMS:,} parameters')

def prompt(task, lang, text): return f'{task} {lang}: {text}'
ex = [(prompt('topic', l, t), y) for l, t, y in zip(tr.language, tr.text, tr.label)] +      [(prompt('headline', l, t), y) for l, t, y in zip(tr.language, tr.text, tr.headline)]

def collate(b):
    x = tk([s for s, _ in b], max_length=MAXIN, truncation=True, padding=True, return_tensors='pt')
    y = tk(text_target=[str(t) for _, t in b], max_length=40, truncation=True, padding=True, return_tensors='pt').input_ids
    y[y == tk.pad_token_id] = -100
    return x.to('cuda'), y.to('cuda')

dl = torch.utils.data.DataLoader(ex, batch_size=4, shuffle=True, collate_fn=collate)
opt = Adafactor(model.parameters(), lr=1e-3, relative_step=False, scale_parameter=False)
steps_per_epoch = -(-len(dl)//ACC_STEPS)
sched = get_linear_schedule_with_warmup(opt, num_warmup_steps=int(0.06*steps_per_epoch*EPOCHS), num_training_steps=steps_per_epoch*EPOCHS)

@torch.no_grad()
def predict(df):
    model.eval(); topics, heads = [], []
    for task, out, kw in [('topic', topics, dict(max_new_tokens=6, num_beams=1)),
                          ('headline', heads, dict(max_new_tokens=32, num_beams=6, length_penalty=1.0, no_repeat_ngram_size=3))]:
        for i in range(0, len(df), 16):
            c = df.iloc[i:i+16]
            x = tk([prompt(task, l, t) for l, t in zip(c.language, c.text)], max_length=MAXIN,
                   truncation=True, padding=True, return_tensors='pt').to('cuda')
            out += tk.batch_decode(model.generate(**x, **kw), skip_special_tokens=True)
    topics = [t.strip().lower() if t.strip().lower() in LABELS else maj for t in topics]
    heads = [' '.join(h.split()) or lead(t) for h, t in zip(heads, df.text)]
    return topics, heads

best_final, best_state = -1, None
model.train(); T1 = time.time()
for ep in range(EPOCHS):
    tot = 0
    opt.zero_grad()
    for i, (x, y) in enumerate(dl):
        loss = model(**x, labels=y).loss / ACC_STEPS
        loss.backward(); tot += loss.item()*ACC_STEPS
        if (i+1) % ACC_STEPS == 0 or i == len(dl)-1:
            opt.step(); sched.step(); opt.zero_grad()
        if i % 400 == 0: print(f'ep{ep+1} step {i}/{len(dl)} loss {loss.item()*ACC_STEPS:.3f} | {(time.time()-T1)/60:.1f} min', flush=True)
    print(f'== epoch {ep+1} done: avg loss {tot/len(dl):.4f} ==', flush=True)
    dt, dh = predict(dv)
    epoch_final = evaluate(dv, dt, dh).loc['ALL', 'Final']
    print(f'   dev Final after epoch {ep+1}: {epoch_final:.4f}', flush=True)
    if epoch_final > best_final:
        best_final = epoch_final
        best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        model.save_pretrained('/kaggle/working/mt5_best'); tk.save_pretrained('/kaggle/working/mt5_best')  # v6: persist to disk too
        print(f'   -> new best, checkpoint saved (memory + disk)', flush=True)
    model.train()

model.load_state_dict(best_state); model.cuda()
print(f'Loaded best checkpoint: dev Final = {best_final:.4f}')
del opt, dl, sched; torch.cuda.empty_cache()

config.json:   0%|          | 0.00/702 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/376 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/284 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

582,401,280 parameters
ep1 step 0/2670 loss 10.951 | 0.0 min
ep1 step 400/2670 loss 5.699 | 3.8 min
ep1 step 800/2670 loss 4.520 | 7.7 min
ep1 step 1200/2670 loss 2.845 | 11.5 min
ep1 step 1600/2670 loss 2.898 | 15.4 min
ep1 step 2000/2670 loss 2.816 | 19.2 min
ep1 step 2400/2670 loss 3.785 | 23.1 min
== epoch 1 done: avg loss 4.4284 ==
   dev Final after epoch 1: 0.6459

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

   -> new best, checkpoint saved (memory + disk)
ep2 step 0/2670 loss 2.826 | 28.6 min
ep2 step 400/2670 loss 1.287 | 32.5 min
ep2 step 800/2670 loss 2.286 | 36.3 min
ep2 step 1200/2670 loss 2.524 | 40.2 min
ep2 step 1600/2670 loss 2.495 | 44.0 min
ep2 step 2000/2670 loss 2.539 | 47.9 min
ep2 step 2400/2670 loss 3.761 | 51.7 min
== epoch 2 done: avg loss 2.3886 ==
   dev Final after epoch 2: 0.6686

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

   -> new best, checkpoint saved (memory + disk)
ep3 step 0/2670 loss 2.151 | 57.4 min
ep3 step 400/2670 loss 2.822 | 61.2 min
ep3 step 800/2670 loss 1.875 | 65.0 min
ep3 step 1200/2670 loss 1.494 | 68.9 min
ep3 step 1600/2670 loss 2.873 | 72.7 min
ep3 step 2000/2670 loss 2.285 | 76.6 min
ep3 step 2400/2670 loss 2.193 | 80.4 min
== epoch 3 done: avg loss 2.0498 ==
   dev Final after epoch 3: 0.6763

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

   -> new best, checkpoint saved (memory + disk)
ep4 step 0/2670 loss 1.806 | 86.0 min
ep4 step 400/2670 loss 2.020 | 89.9 min
ep4 step 800/2670 loss 1.340 | 93.7 min
ep4 step 1200/2670 loss 2.300 | 97.6 min
ep4 step 1600/2670 loss 1.329 | 101.4 min
ep4 step 2000/2670 loss 2.183 | 105.3 min
ep4 step 2400/2670 loss 2.258 | 109.2 min
== epoch 4 done: avg loss 1.7465 ==
   dev Final after epoch 4: 0.6777

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

   -> new best, checkpoint saved (memory + disk)
ep5 step 0/2670 loss 0.758 | 114.7 min
ep5 step 400/2670 loss 1.993 | 118.6 min
ep5 step 800/2670 loss 1.830 | 122.4 min
ep5 step 1200/2670 loss 1.363 | 126.3 min
ep5 step 1600/2670 loss 1.116 | 130.1 min
ep5 step 2000/2670 loss 1.310 | 134.0 min
ep5 step 2400/2670 loss 1.028 | 137.8 min
== epoch 5 done: avg loss 1.4174 ==
   dev Final after epoch 5: 0.6623
ep6 step 0/2670 loss 1.385 | 143.3 min
ep6 step 400/2670 loss 0.916 | 147.1 min
ep6 step 800/2670 loss 0.027 | 151.0 min
ep6 step 1200/2670 loss 0.739 | 154.9 min
ep6 step 1600/2670 loss 1.302 | 158.7 min
ep6 step 2000/2670 loss 0.383 | 162.6 min
ep6 step 2400/2670 loss 0.854 | 166.5 min
== epoch 6 done: avg loss 1.2004 ==
   dev Final after epoch 6: 0.6896

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

   -> new best, checkpoint saved (memory + disk)
ep7 step 0/2670 loss 1.175 | 172.1 min
ep7 step 400/2670 loss 0.316 | 176.0 min
ep7 step 800/2670 loss 1.361 | 179.9 min
ep7 step 1200/2670 loss 1.048 | 183.7 min
ep7 step 1600/2670 loss 0.464 | 187.6 min
ep7 step 2000/2670 loss 0.994 | 191.4 min
ep7 step 2400/2670 loss 1.309 | 195.3 min
== epoch 7 done: avg loss 1.0085 ==
   dev Final after epoch 7: 0.6882
ep8 step 0/2670 loss 0.797 | 200.7 min
ep8 step 400/2670 loss 0.847 | 204.5 min
ep8 step 800/2670 loss 0.438 | 208.4 min
ep8 step 1200/2670 loss 1.083 | 212.2 min
ep8 step 1600/2670 loss 0.844 | 216.1 min
ep8 step 2000/2670 loss 1.545 | 219.9 min
ep8 step 2400/2670 loss 0.945 | 223.8 min
== epoch 8 done: avg loss 0.8587 ==
   dev Final after epoch 8: 0.6934

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

   -> new best, checkpoint saved (memory + disk)
Loaded best checkpoint: dev Final = 0.6934

In [4]:
# 4. Predict helper (topic is forced onto the 7 labels, headline is never blank)
@torch.no_grad()
def predict(df):
    model.eval(); topics, heads = [], []
    for task, out, kw in [('topic', topics, dict(max_new_tokens=6, num_beams=1)),
                          ('headline', heads, dict(max_new_tokens=32, num_beams=4, no_repeat_ngram_size=3))]:
        for i in range(0, len(df), 16):
            c = df.iloc[i:i+16]
            x = tk([prompt(task, l, t) for l, t in zip(c.language, c.text)], max_length=MAXIN,
                   truncation=True, padding=True, return_tensors='pt').to('cuda')
            out += tk.batch_decode(model.generate(**x, **kw), skip_special_tokens=True)
    topics = [t.strip().lower() if t.strip().lower() in LABELS else maj for t in topics]
    heads = [' '.join(h.split()) or lead(t) for h, t in zip(heads, df.text)]
    return topics, heads

In [5]:
# 5. Dev evaluation: baseline vs fine-tuned (row ALL = pooled score, rows below = per language)
dt, dh = predict(dv)
final = evaluate(dv, dt, dh)
cmp = pd.concat({'Baseline (majority + lead-12-words)': base, 'Fine-tuned mT5-base': final}, axis=1)
print(cmp.to_string())
cmp

    Baseline (majority + lead-12-words)                  Fine-tuned mT5-base
                                MacroF1 GenScore   Final             MacroF1 GenScore   Final
ALL                              0.0485   0.4555  0.2520              0.8709   0.5129  0.6919
hau                              0.0332   0.4810  0.2571              0.8849   0.5484  0.7167
ibo                              0.0561   0.4507  0.2534              0.8354   0.5049  0.6701
pcm                              0.0902   0.4912  0.2907              0.9582   0.5127  0.7355
yor                              0.0815   0.3944  0.2379              0.8967   0.4658  0.6812

    Baseline (majority + lead-12-words)                  Fine-tuned mT5-base  \
                                MacroF1 GenScore   Final             MacroF1
ALL                              0.0485   0.4555  0.2520              0.8709
hau                              0.0332   0.4810  0.2571              0.8849
ibo                              0.0561   0.4507  0.2534              0.8354
pcm                              0.0902   0.4912  0.2907              0.9582
yor                              0.0815   0.3944  0.2379              0.8967


    GenScore   Final
ALL   0.5129  0.6919
hau   0.5484  0.7167
ibo   0.5049  0.6701
pcm   0.5127  0.7355
yor   0.4658  0.6812

In [6]:
# 6. Test predictions -> submission.csv (2 rows per test row) + model card line
tt, th = predict(te)
sub = pd.DataFrame({'id': [f'{i}_{s}' for i in te.id for s in ('topic', 'headline')],
                    'prediction': [v for a, b in zip(tt, th) for v in (a, b)]})
sub.to_csv('submission.csv', index=False)
assert len(sub) == 2*len(te) and sub.prediction.str.strip().ne('').all()
print('ids match sample_submission:', set(ss.id) <= set(sub.id))
print(f'Model card: {MID} | {NPARAMS:,} params | full fine-tune, fp32, Adafactor, {EPOCHS} epochs, one model for both tasks | total runtime {(time.time()-T0)/60:.0f} min')
sub.head(6)

ids match sample_submission: True
Model card: google/mt5-base | 582,401,280 params | full fine-tune, fp32, Adafactor, 8 epochs, one model for both tasks | total runtime 238 min

                  id                                         prediction
0     yor_0001_topic                                      entertainment
1  yor_0001_headline     Wizkid: Nkechi Blessing ní òun ti kan lẹ́sẹ̀ o
2     yor_0002_topic                                      entertainment
3  yor_0002_headline  Kemi Afolabi: Ọ̀pọ̀ àwọn olólùfẹ́ mi sọra nípa...
4     yor_0003_topic                                      entertainment
5  yor_0003_headline  Portable Ọmọ Olamile: Gbajúmọ̀ olórin tàkasúfè...

## Discussion (write 5-8 sentences after the run)
What moved the merged score (baseline -> fine-tuned) - which task was harder - which language was hardest - your guess why (e.g. tokenizer coverage, training-set size, Pidgin being English-like). Note: dev = 12% of train.csv held out by language, since no separate dev file was provided. A diagnostic check found reference headlines have very low lexical overlap with the source article (mean ROUGE-L 0.062), confirming they are genuinely paraphrased rather than extracted, which caps how high GenScore can realistically go. v6: 320-token inputs, 8 epochs with a warmup+decay LR schedule and gradient accumulation, keeping the best-scoring checkpoint by dev Final across epochs (also saved to disk as a safety net).